import config
import logging
from io import BytesIO
import asyncio
from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

async def generate_images(prompt):
    """
    Generates images using Google Gemini (Nano Banana integration).
    Uses 'gemini-3-pro-image-preview' as requested by user.
    """
    if not config.google_api_key:
        raise ValueError("Google API Key is missing via .env (GOOGLE_API_KEY)")

    def _generate_sync():
        client = genai.Client(api_key=config.google_api_key)
        
        # User specifically provided this model name for Nano Banana integration
        model = "gemini-3-pro-image-preview"
        
        response = client.models.generate_content(
            model=model,
            contents=[
                types.Content(
                    role="user",
                    parts=[
                        types.Part.from_text(text=prompt),
                    ],
                ),
            ],
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
            )
        )
        return response

    try:
        response = await asyncio.to_thread(_generate_sync)
        
        output = []
        if response.candidates and response.candidates[0].content:
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    buf = BytesIO(part.inline_data.data)
                    buf.name = "image.png" 
                    buf.seek(0)
                    output.append(buf)
        
        if not output:
             raise Exception("No image generated by Gemini 3 Pro")
             
        return output

    except Exception as e:
        logger.error(f"Gemini Error: {e}")
        if "404" in str(e):
             logger.error(f"Model '{model}' not found. Please check your API Key and access to Gemini 3 Preview.")
        raise e
