
import logging
from io import BytesIO
from pptx import Presentation
from pptx.util import Inches, Pt

logger = logging.getLogger(__name__)

async def create_presentation(title, slides_content):
    """
    Presentatsiya yaratish
    slides_content: list of dicts:
    [
        {"title": "Slide 1 Title", "content": "Bullet point 1\nBullet point 2"},
        {"title": "Slide 2 Title", "content": "Text content..."}
    ]
    """
    try:
        prs = Presentation()

        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_item = slide.shapes.title
        subtitle = slide.placeholders[1]

        title_item.text = title
        subtitle.text = "Generated by ChatGPT Bot"

        # Content Slides
        for slide_data in slides_content:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes

            # Title
            title_shape = shapes.title
            if title_shape:
                title_shape.text = slide_data.get("title", "No Title")

            # Body
            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            tf.text = slide_data.get("content", "")

        # Save to buffer
        ppt_buffer = BytesIO()
        prs.save(ppt_buffer)
        ppt_buffer.seek(0)
        ppt_buffer.name = f"{title.replace(' ', '_')}.pptx"
        
        return ppt_buffer
    except Exception as e:
        logger.error(f"Error creating PPTX: {e}")
        return None
